### ISSUE TITLE
Wait Endpoint Deprecated

### ISSUE THREAD

**Issue by RentecAaron** [cloudconvert/cloudconvert-php#100]
Cloudconvert has deprecated the wait endpoint when processing a job. It will be shutdown soon on 11/30/2022. https://cloudconvert.com/api/v2/jobs#jobs-wait

![image](https://user-images.githubusercontent.com/68660736/196253747-5e1e50f7-5a7c-4ee0-9d81-bbefad8038ce.png)

------------------------

I'm currently using the method as defined in the readme:

1. Upload
2. Wait
3. Download

------------------------

Do you currently have plans to update this code to handle that change?

**Comment by josiasmontag** [comment]
Yes, the SDK has already implemented this. Just update to the latest version and you are all set.

**Comment by RentecAaron** [comment]
@josiasmontag thank you 👍🏼
