### ISSUE TITLE
Compose Installation Issue

### ISSUE THREAD

**Issue by alexsdesign** [cloudconvert/cloudconvert-php#107]
Hey everyone, 

Running Plesk on Windows 2022 on an Amazon Ec2 instance.

I've tried to install CloudConvert using Plesk's composer feature.
(Basically, download the ZIP file from here, upload to plesk, run their PHP Composer scanner and install)

However on every attempt I hit this problem: 

`Failed to retrieve data for the package 'psr/http-factory-implementation': In ShowCommand.php line 324:`

I've attached a screenshot of the full error message.

Can anyone assist me with this... or is there an alternative way to set this up without using composer (because it sucks on plesk)
![2024-03-05_22-06-29](https://github.com/cloudconvert/cloudconvert-php/assets/1885252/5d574219-75ee-4a98-aba0-b7340ec394d2)

Thanks in advance

Alex

**Comment by alexsdesign** [comment]
Additional note... no files were adjusted or changed... literally downloaded zip, uploaded to Plesk and unzipped.

**Comment by josiasmontag** [comment]
This SDK cannot be installed via the ZIP archive. It needs to be installed via composer, see the README.

**Comment by alexsdesign** [comment]
Even when using the provided composer.json file from this github, I still receive the error message above.

**Comment by alexsdesign** [comment]
As we are using Plesk I'm unable to run a composer command... I can only run it via the .json file provided by this github.

**Comment by alexsdesign** [comment]
Here is a video link of just using the composer.json file... 
You'll see it fails when it reaches the PSR/Http Factory

https://drive.google.com/file/d/1537CgUpu4Qwg0AkQ586hbB_0weoHZoge/view?usp=drivesdk
