### ISSUE TITLE
The required option "api_key" is missing.

### ISSUE THREAD

**Issue by ManojPremarathna** [cloudconvert/cloudconvert-php#108]
This is working fine on my local but when it is live this issue is coming
Key added to env also try with config file

`if($audio['file']->getClientOriginalExtension() != "mp3") {

                    $job = CloudConvert::jobs()->create(

                        (new Job())`

**Comment by ManojPremarathna** [comment]
@josiasmontag hey what's the solution?

**Comment by josiasmontag** [comment]
This is obviously a problem with your implementation. Please do not use this issue tracker for support requests.
