### ISSUE TITLE
Exception when conversion minutes exceeded

### ISSUE THREAD

**Issue by Toflar** [cloudconvert/cloudconvert-php#11]
Hey,

Is there a possibility the API tells you when your conversion minutes are exceeded? If so, it would be cool if that was a specific exception so I can do something like that:

```php
catch (ConversionMinutesExceededException $e) {
   $this->addError('The images could not be converted because there are no conversion minutes left anymore. Visit https://cloudconvert.com and adjust your plan and buy new minutes!';
}
```

Danke ;-)

**Comment by josiasmontag** [comment]
The API error code in this case is ``402``

You could

```php
catch (ApiException $e) {
    if($e->getCode == 402) {
     //  conversion are exceeded
    }
}
```

or better: create a new ApiException subclass and add it [here](https://github.com/cloudconvert/cloudconvert-php/blob/master/src/Api.php#L136).

Feel free to add a pull request for this.
