### ISSUE TITLE
The api doesn't work or show notification on my user account.‏

### ISSUE THREAD

**Issue by codeovermatter** [cloudconvert/cloudconvert-php#13]
Dear @cloudconvert,
Today I've written code that uses the **php wrapper** for CloudConvert.org, but it seems that I can't get it to work.
besides that There aren't any signs on my CloudConvert's user **dashboard** that indicate the use of the mentioned api.

I Also tried Converting with the auto-generated GET request from https://cloudconvert.com/apiconsole, However I mostly encounter the following response:

```HTTP
 {"id":"Gn4NJ3DgbXSyhziKf1tc","url":"//hostprmxl2.cloudconvert.com/process/Gn4NJ3DgbXSyhziKf1tc","percent":-1,"message":"Download from FTP failed (code undefined):
Timeout while connecting to server","step":"error","starttime":1434246957,"expire":1434248767,"input":
{"type":"ftp","filename":"284.docx","name":"284","ext":"docx"},"output":
{},"endtime":1434246967,"minutes":0,"code":400}
```

I'm attaching my code for further investigation on that matter(the asterisks are used to protect sensitive data:

```PHP
$api = new Api("***-***************************************************************************");
$api->convert([
    "input" => [
        "ftp" => [
            "host" => "ftp.***********.com",
            "port" => "21",
            "user" => "mxnsnjfc",
            "password" => "********************",
        ],
    ],
    "output" => [
        "ftp" => [
            "host" => "ftp.************.com",
            "port" => "21",
            "user" => "mxnsnjfc",
            "password" => "******************************",
            "path" => "public_html/word/$id/img/",
        ],
    ],
    "inputformat" => $extension,
    "outputformat" => "jpg",
    "file" => "public_html/word/$id/$id.$extension",
])
->wait();
```

Thanks in advance,
Ed Smith.

**Comment by josiasmontag** [comment]
The error says ``Timeout while connecting to server``, which means our API can somehow not reach your Host ftp.****.com. Is this FTP host publicly available? (Firewall?). For further investigation please send me the full FTP hostname to support@cloudconvert.com.

**Comment by codeovermatter** [comment]
In order to get your cloudconvert up and running you'll need  to do as follow:
1)allow ftp requests from cloudconvert.
2)write ftp server as an ipv4 address:
 ```php
"ftp" => [
            "host" => "1.1.1.1", //this should be your ftp server ip.
```
