### ISSUE TITLE
api file i can t read

### ISSUE THREAD

**Issue by martam9** [cloudconvert/cloudconvert-php#15]
error Reference #50.2c89ef50.1437761290.f6a211b https://fbcdn-video-o-a.akamaihd.net/hvideo-ak-xpa1/v/t42.3356-2/11656653_1155257631167744_870630002_n.mp4/video-1437496710.mp4.mp4?vabr=161458&oh=8df2cf2f8d5b81c14a00faccc3d4ec70&oe=55AFCA19&__gda__=1437605926_1cfc3a8372c86616f8a69c06c352fb8c&dl=1
https://drive.google.com/file/d/0B-9-pgolTtBFOGs5RUlmR3owV1k/view?usp=sharing
https://drive.google.com/file/d/0B-9-pgolTtBFOGs5RUlmR3owV1k/view

https://drive.google.com/file/d/0B-9-pgolTtBFOGs5RUlmR3owV1k/view?usp=docslist_api

**Comment by josiasmontag** [comment]
Your issue does not contain any reasonable content. You can reopen an issue with a detailed description.

**Comment by martam9** [comment]
I am not with my portable and i cannot see what my content was, is it empty?

2015-08-05 10:28 GMT+02:00 Josias Montag <notifications@github.com>:

> Your issue does not contain any reasonable content. You can reopen an
> issue with a detailed description.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudconvert/cloudconvert-php/issues/15#issuecomment-127913593>
> .
>



-- 
MM
