### ISSUE TITLE
Unable to install using composer

### ISSUE THREAD

**Issue by atul-ebizon** [cloudconvert/cloudconvert-php#16]
Hi,

I'm trying to install cloudconvert-php package on my local system ubuntu 14.04.
To install this package following are the steps that I've done.

1. Created project directory in /var/www/htm/ folder named "cloud-convert"
2. Download cloudconvert-php package and extracted into "cloud-convert" directory
3. Installed composer globally using https://getcomposer.org/doc/00-intro.md#globally
4. Run command "composer install"

I did all above but it is throwing an error, Please see attached image for error.
![cloud-convert-installation-error](https://cloud.githubusercontent.com/assets/10229722/9851611/313c8c66-5b17-11e5-8e3a-453fc35f923c.png)

Please guide me if I am missing something.

Thanks In Advance
Atul

**Comment by atul-ebizon** [comment]
I fixed this by adding these lines
"repositories": {
        "packagist": {"url": "https://packagist.org", "type": "composer"}
}
into composer.json file.

Hope it will be helpful for others.

Thanks
Atul

**Comment by josiasmontag** [comment]
Thanks for sharing!
