### ISSUE TITLE
Library missing file

### ISSUE THREAD

**Issue by moerg** [cloudconvert/cloudconvert-php#18]
Hi!
I try to use your PHP library directly from Github but there's a missing file (/vendor/autoload.php) in your package.

Can it be installed without composer? If so, how could I proceed?

Thanks!

**Comment by josiasmontag** [comment]
Hi,

If you don't want to use composer, please download the .phar (which is basically a ZIP file) file from the releases tab. This phar file also contains the autoload.php. See [here](https://github.com/cloudconvert/cloudconvert-php#install-with-phar) how to use it.
