### ISSUE TITLE
Any plans to use guzzle 6?

### ISSUE THREAD

**Issue by m4tthumphrey** [cloudconvert/cloudconvert-php#21]
In dependency hell at the moment!

**Comment by josiasmontag** [comment]
I did a quick try on upgrading Guzzle but it seems to be more complicated than expected. We definitely want to avoid changes on the interfaces of the wrapper and we want to keep support for Guzzle 5. 

In long term we will support Guzzle 6 but unfortunately I cannot give any schedule for this. In the mean time you could:
a) Try modifying the wrapper on your own
b) Use both Guzzle 5 and 6 in your project
c) Use the alternative [laravel PHP wrapper](https://github.com/robbiepaul/cloudconvert-laravel), which does already support Guzzle 6

**Comment by m4tthumphrey** [comment]
Guzzle 5 and 6 use the same namespace so thats a no go. I also had issues using the legacy laravel wrapper (I'm on laravel 4.2 still).

I'm just using guzzle 6 with the raw endpoints, not ideal but still works fine. Hopefully one day you can upgrade.

**Comment by m4tthumphrey** [comment]
@josiasmontag Ok so it was actually quote trivial to get guzzle 6 to work without changing any of the wrapper. You can see it [here](https://github.com/m4tthumphrey/cloudconvert-php/tree/guzzle-6). I haven't written any tests yet but I'm assuming you will want to upgrade to guzzle 6 officially at some point? 5.x is currently [maintained](https://github.com/guzzle/guzzle#version-guidance) but will not be forever. For now I'm going to just use my repo but would be cool to see the opportunity to get this merged (once tests are present) one day.

**Comment by Solinx** [comment]
@josiasmontag 
Today I found myself in the same position as m4tthumphrey: dependency hell. 

While I could use the alternative Laravel wrapper, I'd prefer to continue using your package. Could you please merge the solution provided by m4tthumphrey? Thanks!

**Comment by m4tthumphrey** [comment]
@Solinx You can just use my fork in the meantime if you're not already...

```json
    "require": {
        "cloudconvert/cloudconvert-php": "dev-guzzle-6"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/m4tthumphrey/cloudconvert-php"
        }
    ]
```

**Comment by josiasmontag** [comment]
Thanks for your work @m4tthumphrey here. I just merged your work in a separate branch and I started on completing it (tests...).

**Comment by m4tthumphrey** [comment]
I just noticed @josiasmontag! Excellent, thank you!

**Comment by Solinx** [comment]
@josiasmontag @m4tthumphrey Awesome! Thanks to the both of you!

**Comment by josiasmontag** [comment]
Version 2.2 is now using Guzzle 6.
