### ISSUE TITLE
Convert videos with fixed width and set the height proportionally.

### ISSUE THREAD

**Issue by ermiri** [cloudconvert/cloudconvert-php#22]
Hi,
I have been used this api for more than a year.But i have to run some test because my videos are not showed well on smart tv.My videos are 16/9 and sometimes on smart tv the picture is stretched.
For now i use this configuration:

$process -> setOption("converteroptions[video_codec]","H264");
		$process -> setOption("converteroptions[video_resolution]","768x432");
		$process -> setOption("converteroptions[video_ratio]","16:9");
		$process -> setOption("converteroptions[video_profile]","baseline");
		$process -> setOption("converteroptions[video_profile_level]","3.0");
		$process -> setOption("converteroptions[video_crf]","0");
		$process -> setOption("converteroptions[faststart]","true");
		$process -> setOption("converteroptions[audio_bitrate]","80");
		$process -> setOption("converteroptions[audio_channels]","1");
		$process -> setOption("converteroptions[audio_codec]","AAC");

Can you tell me how to keep width 768 and let height in proportionally with aspect ratio?
I mean using this api or at least a ffmpeg command(that have all this options) so i can use as a Custom Command in this api.
Thanks

**Comment by josiasmontag** [comment]
Sorry for the delayed reply. Besides that you are using a very old version of the PHP wrapper, this issue is not related to cloudconvert-php. For such general CloudConvert questions please write a Mail to support@cloudconvert.com.
