### ISSUE TITLE
Fatal error: PayloadTooLargeError: too many parameters

### ISSUE THREAD

**Issue by bikashgit** [cloudconvert/cloudconvert-php#28]
> Fatal error: Uncaught exception 'CloudConvert\Exceptions\ApiException' with message **'PayloadTooLargeError: too many parameters'** in /home1/talendro/public_html/test/pdfconvert/src/Api.php:148 Stack trace: #0 /home1/talendro/public_html/test/pdfconvert/src/Api.php(169): CloudConvert\Api->rawCall('GET', '//hostq3ua8k.cl...', Array, false) #1 /home1/talendro/public_html/test/pdfconvert/src/ApiObject.php(60): CloudConvert\Api->get('//hostq3ua8k.cl...', Array, false) #2 /home1/talendro/public_html/test/pdfconvert/src/Process.php(105): CloudConvert\ApiObject->refresh(Array) #3 /home1/talendro/public_html/test/pdfconvert/generate.php(54): CloudConvert\Process->wait() #4 {main} thrown in /home1/talendro/public_html/test/pdfconvert/src/Api.php on line 148

Below is my code which I used, please suggest on this which parameter need to be added or removed.

$api = new Api("API_KEY");
$api->convert([
			"inputformat" => "$extension",
			"outputformat" => "pdf",
			"input" => "upload",
			"file" => fopen('upload/docs/'.$newfilename, 'r'),
			])
			->wait()
			->download();

Note : It is working fine in localhost when run in same code in server its being comes above error thank you for advance.

**Comment by josiasmontag** [comment]
Is this issue reproducible on your server or does it happen occasionally? Are there different PHP versions used on localhost/the server?

**Comment by bikashgit** [comment]
Thank you @Josiam , is the issue caused by PHP version ? in my localhost PHP 5.5.37 and on the server its PHP Version 5.4.45. could you please assist on this.

**Comment by josiasmontag** [comment]
Yes this is the problem. The current version of the CloudConvert PHP wrapper requires PHP >=5.5.

**Comment by bikashgit** [comment]
Oh Strange thank you again , we would upgrade the version in server..:)
