### ISSUE TITLE
Callback Not Working

### ISSUE THREAD

**Issue by jAddict7** [cloudconvert/cloudconvert-php#29]
Dear Team,
Thanks for the awesome plugin. We are trying to implement **Callback** option for our conversion, but we never got hooked back,
$callback = "http://example.com/converted"

`$api = new Api("***");
$process = $api->createProcess([
    "inputformat" => "pdf",
    "outputformat" => "jpg",
]);
$process->start([
    "outputformat" => "jpg",
    "converteroptions" => [
        "quality" => 75,
    ],
    "input" => "upload",
    "file" => fopen($filePath, "r"),
    "callback" => $callback
]);`

**Comment by josiasmontag** [comment]
This seems to be an issue with your callback URL and not related to the PHP wrapper. Please send an email with your full callback URL to support@cloudconvert.com. Thanks.
