### ISSUE TITLE
page number not showing in new generated pdf file

### ISSUE THREAD

**Issue by bikashgit** [cloudconvert/cloudconvert-php#30]
Hi ,

Can you please confirm , My DOC file has been converted successful into PDF but  not showing the page number in the file . I need to know which parameter need to be added for page number to be shown.  below is my code . please help on this.

$api = new Api("XXXXX");
$api->convert([
"inputformat" => "$extension",
"outputformat" => "pdf",
"input" => "upload",

"file" => fopen('upload/docs/'.$newfilename, 'r'),

])
->wait()

->download();

any help would be appreciate

**Comment by josiasmontag** [comment]
This issue is not related to the PHP wrapper. Please provide your DOC file for further investigation to support@cloudconvert.com.
