### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by stekla79** [cloudconvert/cloudconvert-php#31]
Hi, 
I'm using the wrapper and Cloudconvert to convert SVG charts to EMF charts. The conversion works and the file gets converted and stored on cloudconvert. But I don't seem to be able to initiate the download. 

Here is my code. 

<?php
require 'phar://'. $_SERVER['DOCUMENT_ROOT'] .'/_inc/cloudconvert/cloudconvert-php.phar/vendor/autoload.php';
use \CloudConvert\Api;
$api = new Api("**************");

$api->convert([
        'inputformat' => 'svg',
        'outputformat' => 'emf',
        'input' => 'download',
        "file" => "http://****/operationsChart.svg",
        "save" => true,
        "download" => true
    ])
->wait()
->download();
?>

Am I missing something essential?

**Comment by josiasmontag** [comment]
No error thrown? Most likely the file is saved in the current working/temp directory. Try to set the wanted output path:
``
->download("/path/to/output.emf");
``

**Comment by stekla79** [comment]
Thanks for the quick reply!
No error is thrown with the code above. 

If I try to set the path with the following code
`->download('/data/baagede/output.emf');`

This error is thrown: 
Warning: fopen(/data/baagede/output.emf): failed to open stream: No such file or directory in phar:///storage/content/51/132251/fiskdata.se/public_html/_inc/cloudconvert/cloudconvert-php.phar/src/Process.php on line 135 Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid resource type: boolean' in phar:///storage/content/51/132251/fiskdata.se/public_html/_inc/cloudconvert/cloudconvert-php.phar/vendor/guzzlehttp/psr7/src/functions.php:113 Stack trace: #0 phar:///storage/content/51/132251/fiskdata.se/public_html/_inc/cloudconvert/cloudconvert-php.phar/src/Process.php(157): GuzzleHttp\Psr7\stream_for(false) #1 phar:///storage/content/51/132251/fiskdata.se/public_html/_inc/cloudconvert/cloudconvert-php.phar/src/Process.php(135): CloudConvert\Process->downloadStream(false, NULL) #2 /storage/content/51/132251/fiskdata.se/public_html/adm/report/ajax/convertSVG-EMF.php(53): CloudConvert\Process->download('/data/baagede/o...') #3 {main} thrown in phar:///storage/content/51/132251/fiskdata.se/public_html/_inc/cloudconvert/cloudconvert-php.phar/vendor/guzzlehttp/psr7/src/functions.php on line 113

**Comment by josiasmontag** [comment]
Please make sure the directory exists and is writeable.

**Comment by stekla79** [comment]
Should it be an absolute or relative path? I will set the path dynamically depending on the source
 
`$_SERVER['DOCUMENT_ROOT'] . '/path-to-folder/filename.ext'`
`'/path-to-folder/filename.ext'`

**Comment by josiasmontag** [comment]
``$process->download()`` saves the output file locally on your server. If you want to serve the output file to your users, this is thing of your implementation. Alternatively you can point your users directly to ``$process->output->url``.
