### ISSUE TITLE
Multiple output files Download not working

### ISSUE THREAD

**Issue by gauravcanon** [cloudconvert/cloudconvert-php#32]
According to your documentation Multiple output conversion is not working as mentioned in your API documentation 
Getting error 

> warning invalid argument supplied for foreach() 

My code looks like this 

```
<?php
	require __DIR__ . '/vendor/autoload.php';
	use \CloudConvert\Api;
	$api = new Api("APIKEY");
	if(isset($_POST['submit'])){
		$fileName = $_FILES["file"]["name"];
		$fileFormat = end((explode(".", $fileName)));
		$fileBaseName = explode(".", $fileName);
		$requiredFormat = $_POST['required_format'];
		$filePath = $_FILES["file"]["tmp_name"];
		if (!file_exists('original_file')) {
			mkdir('original_file', 0777, true);
		}
		move_uploaded_file($filePath,"original_file/".$fileName);
		
		$process = $api->createProcess([
    		"inputformat" => $fileFormat,
    		"outputformat" => $requiredFormat,
    		
		]);
		
		$process->start([
    		"wait" => true,
    		"save"=> true,
    		"input" => "upload",
    		"file" => fopen("original_file/".$fileName, 'r'),
    		"filename" => $fileName,
   		"outputformat" => $requiredFormat,
		]);
	
               // This is not working
		foreach ($process->output->files as $file) {
     		$process->download($fileBaseName[0] . "." . $requiredFormat, $file);
		}
			// or:
                 this is working
		$process->downloadAll('./tests/');
```

complete code is [here](http://pastebin.com/5V4bUPyS)

Maybe I am doing anything wrong I want that multiple files zip to be downloaded

**Comment by josiasmontag** [comment]
Did you check if there are multiple output files for this particular conversion? Is `$process->output->files ` an array?

**Comment by gauravcanon** [comment]
Yes there are 10 multiple output

**Comment by josiasmontag** [comment]
If you want the ZIP file only, you can use `$process->download("output.zip");`

**Comment by gauravcanon** [comment]
Problem is it will only download zip file I want to download file whatever output is coming e.g ,
1) If user converting **doc to pdf** downloading pdf file it is working fine 
2) but according to documentation of API of multi pages pdf conversion to jpg is not getting downloaded in zip format it is only working in using `downloadAll()`, which downloads separate file.

**Comment by josiasmontag** [comment]
Sorry, your comments are really hard to understand.

`$process->download()` will download a single file, if there is only one output file. It will download a ZIP file, if there are multiple files.

If you want to offer a download of the output file, you don't need to download it on your server. You can redirect the user:
```php
header ("Location: " . $process->output->url); 
```

**Comment by gauravcanon** [comment]
Really very sorry for bas comments , thanks for help I will try this and update you soon , thanks for quick responses
