### ISSUE TITLE
unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by wajipk** [cloudconvert/cloudconvert-php#33]
Hi, i am using cloudconvert for first time. 
But i am getting and error "**Parse error: syntax error, unexpected 'use' (T_USE)**"

My code:
```
require 'phar://cloudconvert-php.phar/vendor/autoload.php';
use CloudConvert\Api;
$api = new Api("apikey");
```
I don't know why it is coming this error should i need to include anything else?

**Comment by josiasmontag** [comment]
See: http://stackoverflow.com/questions/33342994/unexpected-use-t-use-when-trying-to-use-composer
