### ISSUE TITLE
Default mode is not "convert"

### ISSUE THREAD

**Issue by dragu** [cloudconvert/cloudconvert-php#34]
Hi,

I send the request to API by:

```
		$process = $this->api->createProcess([
			'inputformat' => 'gif',
		]);

		$process->start([
			'outputformat' => 'mp4'
			'input' => 'download',
			'files' => [
				'http://replygif.net/i/486.gif',
				'http://replygif.net/i/1528.gif'
			],
			'callback' => $callbackUrl,
		]);
```

And I get to my callback url:

```
array (
  'id' => 'nwmjWLJDrVyAQc9lpEev',
  'url' => '//host123d1qe.cloudconvert.com/process/nwmjWLJDrVyAQc9lpEev',
  'step' => 'error',
)
```

The error message is: `Conversion type not supported: gif to mp4 (mode archive)`

It works when I add 'mode' key with 'convert' value

```
		$process->start([
			'mode' => 'convert',
			'outputformat' => 'mp4',
			'input' => 'download',
			'files' => [
				'http://replygif.net/i/486.gif',
				'http://replygif.net/i/1528.gif'
			],
			'callback' => $callbackUrl,
		]);
```

[According to the documentation 'convert' is default value.](https://cloudconvert.com/api/conversions#status)

**Comment by josiasmontag** [comment]
Only 1 input file is supported for `convert` mode. To convert multiple files, you need to start multiple conversions.
If you provide multiple input files and if you do not set the `mode` parameter, it defaults to `archive`.
