### ISSUE TITLE
how to get width/height of a converted video in output callback api ??

### ISSUE THREAD

**Issue by vsolanki888** [cloudconvert/cloudconvert-php#35]
hiii Alll, 
      I just started using cloudconvert service and all conversions are working properly but one thing that i am missing, I am using cloudconvert callback api and i want something like i want default height, width and duration of a converted video after conversion finishes via callback api as a response at the last
Can anybody help me please ??

**Comment by josiasmontag** [comment]
The conversion API does not return this information. To get file information use the [info mode](https://cloudconvert.com/api/info).

**Comment by vsolanki888** [comment]
@josiasmontag i have tried but it does not give me the below json in the response:

[{
    "id": "bcbreazxcfesccdddd",
    "url": "//host123d1qk.cloudconvert.com/process/dbndd5522te",
    "expire": 1487961371,
    "percent": 100,
    "message": "Saved file to S3",
    "step": "finished",
    "starttime": 1487918166,
    "output": {
        "filename": "new.gif",
        "ext": "gif",
        "size": 5560163,
        "type": "s3"
    },
    "input": {
        "filename": "new.3gp",
        "name": "new",
        "ext": "3gp"
    },
    "converter": {
        "mode": "convert",
        "format": "gif",
        "type": "ffmpeg",
        "options": {
            "trim_to": null,
            "trim_from": null,
            "video_codec": "GIF",
            "video_resolution": null,
            "video_ratio": null,
            "video_fps": null,
            "thumbnail_format": null,
            "thumbnail_size": null,
            "thumbnail_count": null,
            "strip_metatags": null,
            "video_transpose": null,
            "command": null
        }
    },
    "group": "video",
    "minutes": 1,
    "endtime": 1487918171
}]

And i dont get actual height, width and duration of a input video ? is there any other way ?
