### ISSUE TITLE
how to get more info about the input media(video) ? 

### ISSUE THREAD

**Issue by vsolanki888** [cloudconvert/cloudconvert-php#36]
If i use info mode then i get only below parameters:

"input": {
"filename": "new.3gp",
"name": "new",
"ext": "3gp"
}

but i want actual dimension and duration of that input video, how can i get it?

**Comment by josiasmontag** [comment]
You can get all file information using `$process->info`. Please restrain from using the Github issues for support questions and use support@cloudconvert.com instead.
