### ISSUE TITLE
Callback not downloading

### ISSUE THREAD

**Issue by bmorerob** [cloudconvert/cloudconvert-php#38]
I am trying to use the callback method to download files into dynamically created folders, however the download is not working.

I am trying to pass an id as part of the callback to work out where to download the files.

```
try {
    $api->convert([
    'inputformat' => $filetype,
    'outputformat' => $output,
    'input' => 'download',
    'file' => SITE_ROOT.'upld/'.$id_content.'/'.$upfile,
    'callback' => SITE_ROOT.'admin/callback.php?id='.$id_content
]);
```

Inside my `callback.php` I have the following code:

```
require 'phar://cloudconvert-php.phar/vendor/autoload.php';
use \CloudConvert\Api;
use \CloudConvert\Process;
$api = new Api("[myapicode]");

$id = $_GET['id'];

$process = new Process($api, $_REQUEST['url']);
$process->refresh()->downloadAll("../upld/".$id."/");
```

**Comment by josiasmontag** [comment]
Please refrain from using github issues for general support requests. As suggested earlier, use the contact form or our support email for questions regarding your implementation.
