### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by bilal603** [cloudconvert/cloudconvert-php#40]
Hi;
I did all steps but I have a error.

PHP Parse error:  syntax error, unexpected 'use' (T_USE)

Composer.json

{
    "name": "cloudconvert/cloudconvert-php",
    "description": "PHP Wrapper for CloudConvert APIs",
    "homepage": "https://github.com/cloudconvert/cloudconvert-php",
    "authors": [
        {
            "name": "Josias Montag",
            "email": "josias@montag.info"
        }
    ],
    "require": {
        "guzzlehttp/guzzle": "6.*"
    },
    "require-dev": {
        "phpunit/phpunit": "4.0.*",
        "phpdocumentor/phpdocumentor": "2.*",
        "squizlabs/php_codesniffer": "1.*",
        "clue/phar-composer": "~1.0"
    },
    "autoload": {
        "psr-4": {"CloudConvert\\": "src/"}
    }
}

**Comment by josiasmontag** [comment]
The `use` statement needs to be on top.  There is no other code allowed beforehand.
