### ISSUE TITLE
Access to process data

### ISSUE THREAD

**Issue by mintzs** [cloudconvert/cloudconvert-php#41]
Hi,

I'm trying to get the input.url data of the process in order to use download mode on a second conversion, but there is no getter for the data. 

An example (motivation) would be exactly the steps described in the [video conversion API example](https://cloudconvert.com/api/videoconversion). It's specifically mentioned (part 2 step 2) to retrieve the url from the input object of the process data but I can't seem to find a way to do so without using reflections or extending the process class and adding a getter for $data which is luckily a protected member of ApiObject from which Process is derived.

Thanks :)

**Comment by josiasmontag** [comment]
```php
$process->input->url
```
... should work. Please note that this only works if the `save` option was set to `true`.

**Comment by mintzs** [comment]
Thanks @josiasmontag, it works.

It would be nice to document those rather hidden properties...
