### ISSUE TITLE
Just Getting Contents rather than downloading

### ISSUE THREAD

**Issue by subodhgitrepo** [cloudconvert/cloudconvert-php#42]
Hi,
I am trying to convert the doc,docx,pdf..  files to .html file and get contents of html file.  I was wondering if we can just get the contents of the file rather than downloading.
Kindly guide me if it is possible. 

If it is not possible then i hope we can send the file to s3 for sure. Kindly guide me through this.

Thanks.

**Comment by josiasmontag** [comment]
Sure, you could do something like this:
```php
$process->wait();
$html = file_get_contents($process->output->url);
```
You can find our documentation about the S3 feature [here](https://cloudconvert.com/api/s3).

**Comment by subodhgitrepo** [comment]
Hi, 
Thanks for the reply.

I tried what you asked me to do. But i get this 
file_get_contents(//host123d1qi.cloudconvert.com/download/~1PUC9D6lRgRKIuQNorl-qw86llQ): failed to open stream: No such file or directory

Here is how i am doing it .

               $api = new Api("****API KEY***");

		$process = $api->createProcess([
		    'inputformat' => $inputFormat,
		    'outputformat' => $outputformat
		]);

		$process->start([
		    'outputformat' => $outputformat,
		    'converteroptions' => [
		        'quality' => 75,
		    ],
		    'input' => 'download',
		    'file' => $file,
		    'callback' => URL::to('/download')

		]);
		echo "converted";
	   	$html = file_get_contents($process->output->url);
	   	var_dump($html);
	   	die();

**Comment by subodhgitrepo** [comment]
I got the solution . I was missing https.

$html = file_get_contents('https:'.$process->output->url);
