### ISSUE TITLE
Fatal error with Combine including a password protected PDF

### ISSUE THREAD

**Issue by lekiend** [cloudconvert/cloudconvert-php#45]
Hi,
If I try to combine multiple files including 1 PDF password protected file, I get a FATAL ERROR.
I would prefer a nice message to return to the user ;-)

`<b>Fatal error</b>: Uncaught exception 'CloudConvert\Exceptions\ApiConversionFailedException' with message 'Syntax Error: Could not merge damaged documents ('/data/AlternatifBienEtre-131-Ao&lt;c3&gt;&lt;bb&gt;t-2017-Alzheimer-le-protocole-qui-a-gueri-huit-malades-sur-dix-SD-tv.1-paszsword.pdf')
' in
phar:cloudconvert-php.phar/src/Api.php:140 Stack trace: #0
phar:cloudconvert-php.phar/src/Api.php(169): CloudConvert\Api-&gt;rawCall('GET', '//host123d1qs.c...', Array, false) #1
phar:cloudconvert-php.phar/src/ApiObject.php(60): CloudConvert\Api-&gt;get('//host123d1qs.c...', Array, false) #2
phar:cloudconvert-php.phar/src/Process.php(105): CloudConvert\ApiObject-&gt;refresh(Array) #3
\visit.immo\dashboard\includes\dropzone.php(105): CloudConvert\Process-&gt;wait() #4 {main} thrown in <b>phar:cloudconvert-php.phar/src/Api.php</b> on line <b>140</b><br />`.

**Comment by josiasmontag** [comment]
It throws an `ApiConversionFailedException` as expected.
You can catch these exceptions and show a message to your users, also see: https://github.com/cloudconvert/cloudconvert-php#catching-exceptions
