### ISSUE TITLE
unable to download output file in php

### ISSUE THREAD

**Issue by vsolanki888** [cloudconvert/cloudconvert-php#46]
May be i am doing a little mistake, In php i am converting pdf to jpg and i am not getting a particular code for downloading the output file via api reference of cloud convert, for that i create a process and then start a process as referred the api document  below is my code:

**solution-1**

```
<?php
require __DIR__ . '/vendor/autoload.php';
	use \CloudConvert\Api;
	$api = new Api("***********************");

	$process = $api->createProcess([
		    "inputformat" => "pdf",
		    "outputformat" => "jpg",
		]);
	$process->start([
	    "input" => "download",
	    "file" => "http://myDomainUrl/test.pdf",
	    "output" => [
	        "s3" => [
	            "accesskeyid" => "**************",
	            "bucket" => "***************",
	            "secretaccesskey" => "****************",
	            "region" => "************"
	        ]
	    ],
	    "save" => true
	]);

	while($process->step != "finished" && $process->step != 'error'){
        $process = $process->refresh();
       	var_dump($process->percent);
       	echo "<br>".$process->step;
       	if($process->percent == 100 && $process->step == "finished"){
       		break;
       	}
    }
    die("converted");
```

above file runs perfectly but it does not download the output file to s3 path that i mentioned, at the end of my code if i check the step it gives me 'finished' and message  = file initialized, But i am not getting what parameter should i pass to download it in my code, if i use 
$process->download("filename.ext"); 
so it gives the message that there is not output file for that, But if i use $app->convert() it works for me but i can not use that one, code like below

**solution-2**

```
<?php
$api = new Api(****************************);
$api->convert([
	    "input" => "download",
	    "file" => "http://myDomainUrl/test.pdf",
	    "output" => [
	        "s3" => [
	            "accesskeyid" => "**************",
	            "bucket" => "***************",
	            "secretaccesskey" => "****************",
	            "region" => "************"
	        ]
	    ],
	    "save" => true
	]);
```

By this above code(solution-2) i am getting the output files on s3, How can i get the output files by the solution-1, please help me

**Comment by josiasmontag** [comment]
You need to set `outputformat` in the `$process->start()` call also:
```php
$process->start([
	    "input" => "download",
	    "outputformat" => "jpg",
...
```

**Comment by vsolanki888** [comment]
opps i missed it in $process->start() thanks @josiasmontag
