### ISSUE TITLE
Getting problem in animated webp image to jpg

### ISSUE THREAD

**Issue by vsolanki888** [cloudconvert/cloudconvert-php#49]
I am converting animated webp image to jpg below is my php code: 

```
<?php
	require __DIR__ . '/vendor/autoload.php';
	use \CloudConvert\Api;
	 
	$api = new Api("**************************");
	 
	$api->convert([
	    "inputformat" => "webp",
	    "outputformat" => "jpg",
	    "input" => "upload",
	    "file" => fopen('inputfile.webp', 'r'),
	])
	->wait()
	->download();
?>
```

When i am executing it, every time it gives me the error message like 
**{"error":"convert: no images defined `/data/test_animation.jpg' @ error/convert.c/ConvertImageCommand/3254.\r\n","code":422}**

If i convert for static webp format then it works fine but only with animated webp format i am facing this issue, do i have to pass the frame number to convert it or write any command ? please correct me where i am wrong.

Thanks

**Comment by josiasmontag** [comment]
Can you provide the webp file to support@cloudconvert.com? We will do some further investigation.

**Comment by vsolanki888** [comment]
@josiasmontag you can test it with any google sample webp animated file because error occurs with all animated webp files like for this  https://res.cloudinary.com/demo/image/upload/fl_awebp/cell_animation.webp

**Comment by hsharma-lsquared** [comment]
@josiasmontag, why not you are using this library http://xahlee.info/img/convert_webp_to_jpg.html,
I am waiting since last year, please add support for webp (both static and animated),

**Comment by josiasmontag** [comment]
Closing this issue as it is rather about CloudConvert itself and not this PHP SDK.
