### ISSUE TITLE
File converted to HTML with no text 

### ISSUE THREAD

**Issue by subodhjack** [cloudconvert/cloudconvert-php#51]
Hi @josiasmontag 
The file attached when converted to HTML has no text present.
Input Format : doc
Output Format : HTML

I even tried in the API CONSOLE of cloud convert : (https://cloudconvert.com/api/console) 

[document.zip](https://github.com/cloudconvert/cloudconvert-php/files/1709904/document.zip)

**Comment by josiasmontag** [comment]
Seems to be a CloudConvert issue directly and not related to the PHP SDK. Please contact support@cloudconvert.com directly.
