### ISSUE TITLE
errors when i uconvert file size more than 60 mb

### ISSUE THREAD

**Issue by tieuutaa** [cloudconvert/cloudconvert-php#59]
i have errors when i convert file pdf size 60mb Client error: `POST https://eliza.infra.cloudconvert.com/process/505c9db3-08c8-425d-8bd5-bb56ff1a5894` resulted in a `400 Bad Request` response: {"id":"505c9db3-08c8-425d-8bd5-bb56ff1a5894","url":"//eliza.infra.cloudconvert.com/process/505c9db3-08c8-425d-8bd5-bb56f (truncated...) How can i fix it this my code  public function convertJPG(Request $request)     {         $files = $request->file('file');          set_time_limit(900);         $ConvertPDF = new CloudConvert();         $ConvertPDF->setApiKey('PUJBbPxiTOWUXxiIUIRiv8ftcM8PpzRTxiWK8CLdqUJvalWydIcpl3nCh3YdIzng');         if ($files) {             if ($this->checkFilePDF($files)) {                 $fileJPGs = [];                 $destinationPath = 'uploads';                 foreach ($files as $file) {                     $fileName = $file->getClientOriginalName();                     $file->move($destinationPath, $fileName);                     $fileJPG = 'uploads/' . str_replace("pdf", "jpg", $fileName);                     $currentFile = "uploads/" . $fileName;                     if (file_exists($currentFile)) {                         $variables = ['name' => 'John Doe', 'address' => 'Wall Street'];                         $success = $ConvertPDF->file($currentFile)->templating($variables)->to($fileJPG);                         $success = true;                     } else {                         $success = false;                     }                 }

**Comment by josiasmontag** [comment]
The response is truncated. What is the full response?

**Comment by tieuutaa** [comment]
}
                if ($success) {
                    Session::put('file', $fileDOCXs);
                    return redirect()->route('dl-download');
                }
            } else {
                Session::put('error', 'File bạn lựa chọn không phải định dạng PDF hoặc kích thước file quá lớn ,<br /> Vui lòng thực hiện lại ');
                return redirect()->route('pdf-to-docx');
            }
        }



        return view('convert-docx');

**Comment by josiasmontag** [comment]
This is not the response body. The issue seems not to be related to this SDK, please ask on StackOverflow instead.
