### ISSUE TITLE
Use without composer

### ISSUE THREAD

**Issue by sundowatch** [cloudconvert/cloudconvert-php#60]
Can I use cloud convert API without composer? I'm using shared server and it doesn't allow to install composer

**Comment by josiasmontag** [comment]
You can: https://github.com/cloudconvert/cloudconvert-php#install-manually

**Comment by RafaelAlbani** [comment]
Hi, i cannot access the link to install manually the library, can you provide a way of doing this?

**Comment by josiasmontag** [comment]
The current version of the SDK can be used with composer only.
