### ISSUE TITLE
Error combining files from S3 to PDF

### ISSUE THREAD

**Issue by RPort71** [cloudconvert/cloudconvert-php#63]
I am trying to take 3 files that have been created and uploaded to S3 and combine them into one PDF and download it to my computer, but I keep getting the following error: `CloudConvert\Exceptions\ApiBadRequestException : Input module [object Object] not found`

I started with a test, which works with the files that CloudConvert supplies for testing, but when I change them to my files, I get the error.  Any help would be very much appreciated.

Here is my code:
```
function testCloudConvert() {
        $api = new Api('123');

        $process = $api->createProcess([
            'mode' => 'combine',
            'inputformat' => 'pdf',
            'outputformat' => 'pdf',
        ]);

        $this->assertNotEmpty($process);
        $jobid = '274526';
        $file1 = 'http://xxx.s3.amazonaws.com/uploads/' . $jobid . '/filename1.pdf';
        $file2 = 'http://xxx.s3.amazonaws.com/uploads/' . $jobid . '/filename2.pdf';
        $file3 = 'http://xxx.s3.amazonaws.com/uploads/' . $jobid . '/filename3.pdf';
        $process->start([
            'mode' => 'combine',
            'input' => [
                'S3' => [
                    'accesskeyid' => 'xxxx',
                    'secretaccesskey' => 'xxxx',
                    'bucket' => 'xxx',
                ]
            ],
            'files' => [
//                '0' => 'https://cloudconvert.com/assets/a521306/testfiles/pdfexample1.pdf',
//                '1' => 'https://cloudconvert.com/assets/a521306/testfiles/pdfexample2.pdf',
                '0' => $file1,
                '1' => $file2,
                '2' => $file3,
            ],
            'outputformat' => 'pdf',
            'wait' => true,
        ]);

        $download = $process->download('outputfileNEW.pdf');
        force_download($download);
    }
```

**Comment by josiasmontag** [comment]
`s3` in `$process->start()` should be lowercase.

**Comment by RPort71** [comment]
> `s3` in `$process->start()` should be lowercase.

Thank you for responding.  I am now getting `CloudConvert\Exceptions\ApiBadRequestException : S3 download failed: The specified key does not exist. (Code: NoSuchKey)`.  I'm guessing that is a problem with one of the keys that I put in?

**Comment by josiasmontag** [comment]
Yes, this error is coming back from AWS.

**Comment by RPort71** [comment]
Thank you!  I really appreciate your help.
