### ISSUE TITLE
File can't be opened after merge

### ISSUE THREAD

**Issue by RPort71** [cloudconvert/cloudconvert-php#64]
I have the following code that takes 3 PDFs and merges them into one.  The code uploads the merged file to S3 and displays it in the web page.  When I click on the file to download and open it, I get a message `Adobe Reader could not open because it is either not a supported file type or because the file has been damaged (for example, it was sent as an email attachment and wasn't correctly decoded).`

Here is the code:

        $api = new Api('*****');

        $process = $api->createProcess([
            'mode' => 'combine',
            'inputformat' => 'pdf',
            'outputformat' => 'pdf',
        ]);

        $file1 = 'uploads/' . $jobid . '/' . $filenameVoucher;
        $file2 = 'uploads/' . $jobid . '/' . $filenameInvoice;
        $file3 = 'uploads/' . $jobid . '/' . $filenameList;
        $process->start([
            'mode' => 'combine',
            'input' => [
                's3' => [
                    'accesskeyid' => '****',
                    'secretaccesskey' => '****',
                    'bucket' => '****',
                ]
            ],
            'files' => [
                '0' => $file1,
                '1' => $file2,
                '2' => $file3,
            ],
            'outputformat' => 'pdf',
            'output' => [
                's3' => [
                    'accesskeyid' => '****',
                    'secretaccesskey' => '****',
                    'bucket' => '****',
                ]
            ],
            'wait' => true,
            'save' => true,
        ]);

        $finalFilename = $filedate . ' COMBINED ' . strtoupper($county) . '.pdf';
        $attachmentid = $this->MJob->getNewAttachmentId();
        $this->S3->saveFile('uploads/' . $jobid . '/' . $finalFilename, $finalFilename, 'application/pdf', false, self::INVOICE_BUCKET);
        $this->MJob->updateAttachment($attachmentid, $jobid, $finalFilename, $finalFilename, 'COMBINATION VOUCHER, INVOICE, LIST', 'application/pdf', 0, '', 0, self::INVOICE_BUCKET);

Any help would be much appreciated!

**Comment by josiasmontag** [comment]
This seems to be a file specific issue and not related to the PHP SDK.
Please send the input files and the broken output file to support@cloudconvert.com. Thanks.
