### ISSUE TITLE
[S3] - How to import multiple files at once with key_prefix optional

### ISSUE THREAD

**Issue by gloryit** [cloudconvert/cloudconvert-php#65]
I can import, convert and export single file on s3. And i read docs cloudconvert api support key_prefix optional for multiple files. But i can't do this. It not work.

And if support multiple with ext files. Can you help me how to you it.

I very thank you so much.

PS: Sorry for my english not good. Plz understand

**Comment by josiasmontag** [comment]
`key_prefix` is for export/s3 tasks only, not for import/s3. 
You cannot import multiple files with one task. You need to create a task for each file individually.

**Comment by gloryit** [comment]
> is for export/s3 tasks only

Thx for your answer. I'll contact with cloudconvert. Because i see it on docshttps://cloudconvert.com/api/v2/import#import-s3-tasks

Or i ask them to update docs. 

Thx you so much

**Comment by josiasmontag** [comment]
Thanks! We will fix this in the api docs.
