### ISSUE TITLE
Would you mind if I added about 15 more lines of example to the "uploading" section

### ISSUE THREAD

**Issue by csev** [cloudconvert/cloudconvert-php#66]
I have finally read between the lines and guessed as to how to start the upload from the user's browser and then wait in while the job is processing, checking status with a simple AJAX request and then downloading the result when complete.  I won't write all the ajax - the critical element is how to start a job, get its ID, let the user press "submit", and then check the job using get(id) in a later request  /response cycle - I get that a webhook does this same thing - but for some of us, a doing this in Ajax lets us use a mechanism we understand and feel more confident about and lets do a bit more error processing, etc.  This would not replace the webhook bits  -just add a few more lines just after the form example.

**Comment by josiasmontag** [comment]
With API v2 it is currently not possible to check the job status on client side (ajax). Doing this would require to expose your API key to the client.

**Comment by csev** [comment]
I will be checking in the server.  Just a few lines of PHP to grab the status given a job id.

**Comment by josiasmontag** [comment]
```php
$cloudconvert->jobs()->get($id);
```
gives the current job status.
