### ISSUE TITLE
Puli Factory is not available

### ISSUE THREAD

**Issue by RafaelAlbani** [cloudconvert/cloudconvert-php#68]
Hi, i am trying to use the library, but getting always the same error message: 

Exception has occurred.
Http\Discovery\Exception\PuliUnavailableException: Puli Factory is not available

I ran the command composer require cloudconvert/cloudconvert-php, and try to use the Jobs class, but it's not working here.

Can someone help me?

**Comment by nickbasham-grayloon** [comment]
I'm receiving this same error.

**Comment by josiasmontag** [comment]
This error comes if it cannot find any `HttpClient`. Please make sure you have Guzzle etc. installed.
Alternatively, you can also pass a HttpClient to the constructor directly:
```php
new CloudConvert([
    'http_client` => $httpClient
]);
```

**Comment by nickbasham-grayloon** [comment]
Ah, gtocha.

I installed the Guzzle adapter with the `composer require cloudconvert/cloudconvert-php php-http/guzzle7-adapter` command, and guzzle7-adapter in turn requires Guzzle, right?

I added Guzzle directly to my project, too, and still hit the same error.

**Comment by DhruviSanghvi** [comment]
You should remove guzzle7-adapter and check with installing `composer require cloudconvert/cloudconvert-php php-http/guzzle6-adapter`
It should work for you!

**Comment by nickbasham-grayloon** [comment]
Hmmm, I'm getting the same error when switching to the guzzle6-adapter.

**Comment by nickbasham-grayloon** [comment]
Sorry, I'm not super familiar with the current states of HTTP clients in PHP…I'm trying to pass in a HttpClient to CloudConvert, but not sure if I have to do that through the adapter, or directly with Guzzle?

I added `use Http\Adapter\Guzzle7\Client as GuzzleAdapter;` and tried `'http_client` => new GuzzleAdapter()`, and `'http_client` => GuzzleAdapter::createWithConfig($config)`, but wasn't getting anywhere.

My composer includes the following:
```
"cloudconvert/cloudconvert-php": "^3.2",
"guzzlehttp/guzzle": "^7.0",
"php-http/guzzle7-adapter": "^1.0",
```

**Comment by josiasmontag** [comment]
Should be fixed with latest version
