### ISSUE TITLE
JsonMapper_Exception with opcache.load_comments enabled

### ISSUE THREAD

**Issue by migueliriano** [cloudconvert/cloudconvert-php#70]
### Issue

In our server, we are using the Opcache to cache the content but when we try to create a `job` we get a `JsonMapper_Exception` of this library.

The cause of this error is because we had the phpdoc comments disabled [opcache.load_comments](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.save-comments), the phpdoc is needed for [jsonmapper](https://github.com/cweiske/jsonmapper) library that is used for this SDK package to map the response from Cloudconvert API.

### Error Log

```
JsonMapper_Exception: JSON property "started_at" in class "CloudConvert\Models\Job" must not be NULL in /home/thechive/public_html/wp-content/plugins/core/vendor/netresearch/jsonmapper/src/JsonMapper.php:207
```
### Workaround

We enabled the option `opcache.load_comments` from the config and we got the SDK works in this environment, but this is something that cost about `20%` of performance in our website, I would like to know if the SDK library can be updated to work without the phpdocs like this case.

**Comment by josiasmontag** [comment]
I do not see any way to make this work without completely replacing `jsonmapper`. This is something we do not want to do at the moment. 

20% performance gain by this Opcache option sounds crazy for me. Maybe some of your other code/packages has "bad" comments/annotations which cause this performance drop?
