### ISSUE TITLE
Authentication issue when uploading file

### ISSUE THREAD

**Issue by yehezkel** [cloudconvert/cloudconvert-php#74]
Since yesterday we are experiencing all tasks been unable to upload the file for conversion, the root of the problem resides on file:
https://github.com/cloudconvert/cloudconvert-php/blob/3.0.5/src/Transport/HttpTransport.php line 202
changing from:
*return $this->sendRequest($request, false);*
to 
*return $this->sendRequest($request, true);*
resolves the authentication error, we are using v3.0.5 but the issue persists even with v3.1.0

**Comment by josiasmontag** [comment]
This has been solved most probably by https://github.com/cloudconvert/cloudconvert-php/commit/f34eca1b047be018425e4407d25d6d61719201b6
