### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by bkonia** [cloudconvert/cloudconvert-php#75]
I'm having trouble installing the SDK via Composer, following your instructions:

```
composer require cloudconvert/cloudconvert-php "guzzlehttp/guzzle:^7.0"
```

 [UnexpectedValueException]
  Could not parse version constraint : Invalid version string ""

```
composer require cloudconvert/cloudconvert-php
```

- Installation request for cloudconvert/cloudconvert-php ^3.1.0 -> satisfiable by cloudconvert/cloudconvert-php[3.1.0].
- cloudconvert/cloudconvert-php 3.1.0 requires php-http/client-implementation ^1.0 || ^2.0 -> no matching package found.

Please advise

**Comment by josiasmontag** [comment]
It should be 
```
composer require cloudconvert/cloudconvert-php guzzlehttp/guzzle "^7.0"
```

**Comment by bkonia** [comment]
After using your revised require statement, I was still getting the second. It turns out, you also have to install
php-http/guzzle7-adapter.

**Comment by josiasmontag** [comment]
`php-http/client-implementation` is a virtual package. guzzle 7.0 also provides this package directly. You might need to install guzzle beforehand though.
