### ISSUE TITLE
is it useful to use PluginClient ?

### ISSUE THREAD

**Issue by olivier34000** [cloudconvert/cloudconvert-php#77]
Hello,

Before creating a PR I would like to know if it's normal to encapsulate the client when we set it with PluginClient. 

https://github.com/cloudconvert/cloudconvert-php/blob/986f2c2666c96175d228d6d69561b67749638b76/src/Transport/HttpTransport.php#L55-L63

The behaviour should be 
```php
if(isset($this->options['http_client'])) {
    return $this->options['http_client']);
}

$httpClientPlugins = [ 
     new HeaderDefaultsPlugin([ 
         'User-Agent' => 'cloudconvert-php/v3 (https://github.com/cloudconvert/cloudconvert-php)', 
     ]), 
     new RedirectPlugin() 
 ]; 
  
 return new PluginClient(Psr18ClientDiscovery::find(), $httpClientPlugins); 
```

**Comment by josiasmontag** [comment]
This is intended. The SDK needs certain plugins such as the RedirectPlugin to function.
