### ISSUE TITLE
i am acing this problem.

### ISSUE THREAD

**Issue by ranahammad415** [cloudconvert/cloudconvert-php#81]
Fatal error: Uncaught CloudConvert\Exceptions\HttpClientException: Unauthenticated. in C:\xampp\htdocs\z\vendor\cloudconvert\cloudconvert-php\src\Exceptions\HttpClientException.php:74 Stack trace: #0 C:\xampp\htdocs\z\vendor\cloudconvert\cloudconvert-php\src\Transport\HttpTransport.php(247): CloudConvert\Exceptions\HttpClientException::unauthorized(Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\z\vendor\cloudconvert\cloudconvert-php\src\Transport\HttpTransport.php(227): CloudConvert\Transport\HttpTransport->handleErrors(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\z\vendor\cloudconvert\cloudconvert-php\src\Transport\HttpTransport.php(149): CloudConvert\Transport\HttpTransport->sendRequest(Object(GuzzleHttp\Psr7\Request)) #3 C:\xampp\htdocs\z\vendor\cloudconvert\cloudconvert-php\src\Resources\JobsResource.php(56): CloudConvert\Transport\HttpTransport->post('https://api.clo...', Array) #4 C:\xampp\htdocs\z\index.php(37): CloudConvert\Resources\JobsResource->create(Object(CloudConvert\Models\Job)) #5 {main} t in C:\xampp\htdocs\z\vendor\cloudconvert\cloudconvert-php\src\Exceptions\HttpClientException.php on line 74

hare is my code
kindly give me solution.

`require('vendor/autoload.php');

      
    
    use \CloudConvert\CloudConvert;
    use \CloudConvert\Models\Job;
    use \CloudConvert\Models\Task;
    
    $cloudconvert = new CloudConvert(['api_key' => 'nOs4bTQSCes1Bnm57YmQWS1wmGZ38lM4KuMmlZp07BKf6mEsrgCFv5TAKonnvE32']);
    

    $job = (new Job())
    ->setTag('myjob-1')
    ->addTask(
        (new Task('import/url', 'import-my-file'))
        ->set('url','https://www.careersupporthub.com/5-Job-Winning-Resume-Tips.php')
    )
    ->addTask(
        (new Task('convert', 'convert-my-file'))
            ->set('input', 'import-my-file')
            ->set('output_format', 'pdf')
            ->set('some_other_option', 'value')
            ->set('input_format', 'pdf')
            ->set('output_format', 'doc')
            ->set('engine', 'bcl')
            ->set('input', 'import-my-file')
            ->set('engine_version', '5.0')
    )
    ->addTask(
        (new Task('export/url', 'export-my-file'))
            ->set('input', 'import-my-file')
            ->set('inline', false)
            ->set('archive_multiple_files', false)
    );

$cloudconvert->jobs()->create($job);`

**Comment by josiasmontag** [comment]
This looks like an API v1 key and not v2. And again, you are leaking your API key.

This is an issue tracker. Please stop using the issue tracker for support questions.

**Comment by ranahammad415** [comment]
i have try much time to contact support. but they do not reply me on my problem.
kindly help me .
is this code is right.
in which method i can got v2 api key.

kindly answer my question.
tnks sir
