### ISSUE TITLE
Getting empty response in ExportUrls from Jobs

### ISSUE THREAD

**Issue by DhruviSanghvi** [cloudconvert/cloudconvert-php#84]
After wait process gets done " $cloudconvert->jobs()->wait($job); "
Getting a blank array in $job->getExportUrls();

**Comment by josiasmontag** [comment]
`$job->getExportUrls()` only works if the job has a successful an `export/url` task.

**Comment by DhruviSanghvi** [comment]
HI @josiasmontag, Yes, but the [Job builder](https://cloudconvert.com/api/v2/jobs/builder) is not working properly. How can I check that?

**Comment by josiasmontag** [comment]
We are not aware of any issues. Please contact support@cloudconvert.com with details.
