### ISSUE TITLE
How to install this just as a php package

### ISSUE THREAD

**Issue by galipmedia** [cloudconvert/cloudconvert-php#9]
Hi Sorry for the noob question but I have tried to place this in my project just by using require('Api.php') but I get an error on " use \CloudConvert\Api; " Is there another way to do this like...
 $Api = new \CloudConvert\Api();
        $api = $Api("api-key");

Really interested t try this but I am not familiar with phar etc. Was hoping to jump in and do a quick test.

**Comment by galipmedia** [comment]
Just found the legacy version which is just a class. Works liked a dream first time. You are the man! Thanks for this amazing service!

**Comment by josiasmontag** [comment]
If you want to use the new version, you can download the phar here: https://github.com/cloudconvert/cloudconvert-php/releases

Place this file in the same folder and use
```php
<?php
require 'phar://cloudconvert-php.phar/vendor/autoload.php';
use \CloudConvert\Api;
$api = new Api("your_api_key");
```
