### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by lukassteiner** [cloudconvert/cloudconvert-php#96]
I want to convert a docx to multiple png files in a zip archive.

For this, I use this code
````
->addTask(
                (new Task('convert', 'convert-my-file'))
                    ->set('input', 'upload-my-file')
                    ->set('input_format', 'docx')
                    ->set('output_format', 'png')
            )
````

How can I configure the output to be a zip archive?
It should be possible according to the API documentation:
https://cloudconvert.com/api/v2/archive#archive-tasks

But I don't see how it is coded with this PHP-API.

Thanks for your help

**Comment by josiasmontag** [comment]
You need to add an `archive` task after the `convert` task.

This is a support request and not an issue of the PHP SDK, therefore I am closing this issue. As a CloudConvert customer, please contact [support@cloudconvert.com](mailto:support@cloudconvert.com) for support.
