### ISSUE TITLE
Idle timeout reached

### ISSUE THREAD

**Issue by sdespont** [cloudconvert/cloudconvert-php#97]
Sometimes, the following error occurred : Idle timeout reached for "https://api.cloudconvert.com/v2/jobs/.../wait", but in the dahsboard I can see that this conversion have been successful.

Is there a way to define the timeout related to `$cloudConvert->jobs()->wait($job); `

**Comment by josiasmontag** [comment]
Sometimes the network stack of your system might automatically time out requests if there is not data transferred for a longer time. 

If you see this regularly I recommend using webhooks instead.
